name: Brady Miller
google_analytics: UA-8316288-1
email_link: mailto:brady.g.miller@gmail.com
pgp_key_link: https://pgp.mit.edu/pks/lookup?op=get&search=0x27DEF05B1A8A6D4F
github_link: https://github.com/bradymiller
linkedin_link: https://www.linkedin.com/in/brady-miller-b807b61b

markdown: kramdown
exclude:
  - LICENSE
  - README.md
  - CNAME
