title: Brady Miller
name: Brady Miller
website_address: http://www.bradymd.com
google_analytics: UA-8316288-1
email: brady.g.miller@gmail.com
pgp_key_link: https://keybase.io/bradymiller/pgp_keys.asc?fingerprint=8a93ddec0e320d5eb8a7994827def05b1a8a6d4f
github_link: https://github.com/bradymiller
twitter_link: https://twitter.com/millerbrady
linkedin_link: https://www.linkedin.com/in/brady-miller-b807b61b
keybase_link: https://keybase.io/bradymiller

markdown: kramdown
exclude:
  - LICENSE
  - README.md
  - CNAME
